apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: app-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
      - image: 080196/app-api:v1
        name: app-api
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-api
spec:
  type: NodePort
  selector:
    app: app-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000